// <auto-generated />
using System;
using AutoDiag.DAL.Context;
using AutoDiag.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoDiag.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240501123233_seeddata-to-models")]
    partial class seeddatatomodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoDiag.DataModels.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.CarSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarSystemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CarSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarSystemName = "Engine Performance Sensors",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4398),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4441)
                        },
                        new
                        {
                            Id = 2,
                            CarSystemName = "Environmental Sensors",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4446),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4447)
                        },
                        new
                        {
                            Id = 3,
                            CarSystemName = "Cooling System Sensor ",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4450),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4451)
                        },
                        new
                        {
                            Id = 4,
                            CarSystemName = "Fuel System Sensor",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4453),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 566, DateTimeKind.Local).AddTicks(4455)
                        });
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.Fault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProblemCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProblemCode");

                    b.HasIndex("UserId");

                    b.ToTable("Faults");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("UserId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<float?>("AvgValue")
                        .HasColumnType("real");

                    b.Property<int?>("CarSystemId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("MaxValue")
                        .HasColumnType("real");

                    b.Property<float?>("MinValue")
                        .HasColumnType("real");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CarSystemId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AvgValue = 2.5f,
                            CarSystemId = 3,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7579),
                            MaxValue = 4.5f,
                            MinValue = 0.5f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7616),
                            SensorName = "Engine Coolant Temperature",
                            Unit = "volts"
                        },
                        new
                        {
                            Id = 101,
                            AvgValue = 2.5f,
                            CarSystemId = 4,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7620),
                            MaxValue = 5f,
                            MinValue = 0f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7622),
                            SensorName = "Fuel Level",
                            Unit = "volts"
                        },
                        new
                        {
                            Id = 102,
                            AvgValue = 90.65f,
                            CarSystemId = 2,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7625),
                            MaxValue = 101.3f,
                            MinValue = 80f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7626),
                            SensorName = "Barometric Pressure",
                            Unit = "kPa"
                        },
                        new
                        {
                            Id = 103,
                            AvgValue = 0f,
                            CarSystemId = 2,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7702),
                            MaxValue = 40f,
                            MinValue = -40f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7704),
                            SensorName = "Air in Tank Temperature",
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 104,
                            AvgValue = 4.5f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7706),
                            MaxValue = 5f,
                            MinValue = 4f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7708),
                            SensorName = "MAF (Mass Air Flow)",
                            Unit = "volts"
                        },
                        new
                        {
                            Id = 105,
                            AvgValue = 140f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7712),
                            MaxValue = 250f,
                            MinValue = 30f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7713),
                            SensorName = "Intake Manifold Pressure",
                            Unit = "kPa"
                        },
                        new
                        {
                            Id = 106,
                            AvgValue = 75f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7716),
                            MaxValue = 112f,
                            MinValue = 37f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7718),
                            SensorName = "Engine Power",
                            Unit = "kW"
                        },
                        new
                        {
                            Id = 107,
                            AvgValue = 45f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7720),
                            MaxValue = 100f,
                            MinValue = 10f,
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 567, DateTimeKind.Local).AddTicks(7722),
                            SensorName = "Engine Load",
                            Unit = "%"
                        });
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.TroubleCode", b =>
                {
                    b.Property<string>("ProblemCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.HasKey("ProblemCode");

                    b.ToTable("TroubleCodes");

                    b.HasData(
                        new
                        {
                            ProblemCode = "P0079",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4277),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4311),
                            ProblemDescription = "Exhaust Valve Control Circuit Low (Bank 2)",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P2004",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4315),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4317),
                            ProblemDescription = "Problem with the Intake Manifold Runner Control (IMRC) actuator, which controls the airflow into the engine",
                            Severity = 6
                        },
                        new
                        {
                            ProblemCode = "P3000",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4319),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4320),
                            ProblemDescription = "Problem with the battery control system",
                            Severity = 8
                        },
                        new
                        {
                            ProblemCode = "P0078",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4322),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4324),
                            ProblemDescription = "Exhaust Valve Control Circuit (Bank 2)",
                            Severity = 3
                        },
                        new
                        {
                            ProblemCode = "P007E",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4326),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4327),
                            ProblemDescription = "Problem with the Charge Air Cooler Temperature Sensor Circuit",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "P2036",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4330),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4332),
                            ProblemDescription = "Problem with the Exhaust Gas Temperature Sensor Circuit",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P007F",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4334),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4335),
                            ProblemDescription = "Typically related to the fuel temperature sensor",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "P18E0",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4337),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4338),
                            ProblemDescription = "Problem with the Fuel Pressure Sensor Circuit",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "P1004",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4341),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4342),
                            ProblemDescription = "Problem with the Intake Valve Control Solenoid Circuit",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P18D0",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4345),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4346),
                            ProblemDescription = "Problem with the Exhaust Valve Control Solenoid Circuit",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P18F0",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4349),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4350),
                            ProblemDescription = "Problem with the Turbocharger Boost Control Solenoid Circuit",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "C1004",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4352),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4353),
                            ProblemDescription = "Related to the Driver Knee Bolster Deployment Control",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "B0004",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4355),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4357),
                            ProblemDescription = "Related to the Driver Knee Bolster Deployment Control",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "U1004",
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4359),
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(4360),
                            ProblemDescription = "Indicates an intermittent Controller Area Network Bus Transmit Performance",
                            Severity = 8
                        });
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.TroubleCodeLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProblemCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("ProblemCode");

                    b.ToTable("TroubleCodeLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9462),
                            Link = "https://www.obd2pros.com/dtc-codes/p0079/",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9492),
                            ProblemCode = "P0079",
                            Title = "P0079 Code - What Does It Mean?"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9496),
                            Link = "https://www.engine-codes.com/p0079.html",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9497),
                            ProblemCode = "P0079",
                            Title = "P0079 Code - Meaning, Causes, & Symptoms"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9499),
                            Link = "https://cartreatments.com/p2004-code-imrc-issue-symptoms-causes-and-fixes/",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9501),
                            ProblemCode = "P2004",
                            Title = "P2004 Code - IMRC Issue"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9503),
                            Link = "https://www.rxmechanic.com/p3000-error-code/",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9504),
                            ProblemCode = "P3000",
                            Title = "P3000 Error Code - What Does It Mean?"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9506),
                            Link = "https://www.troublecodes.net/pcodes/p3000/",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9507),
                            ProblemCode = "P3000",
                            Title = "P3000 - Manufacturer Controlled DTC Bank 1"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9511),
                            Link = "https://www.troublecodes.net/pcodes/p0078/",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9512),
                            ProblemCode = "P0078",
                            Title = "P0078 - Exhaust Valve Control Circuit"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9573),
                            Link = "https://www.obd-codes.com/p007e",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9575),
                            ProblemCode = "P007E",
                            Title = "P007E - Charge Air Cooler Temp. Sensor Circuit"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9577),
                            Link = "https://www.obd-codes.com/p2036",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9578),
                            ProblemCode = "P2036",
                            Title = "P2036 - Exhaust Gas Temp. Sensor Circuit"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9580),
                            Link = "https://partsavatar.ca/p007f-obd-ii-trouble-code-charge-air-cooler-temperature-sensor-bank-1-bank-2-correlation-solution",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9582),
                            ProblemCode = "P007F",
                            Title = "P007F - Charge Air Cooler Temp. Sensor Correlation"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9586),
                            Link = "http://p18e0.engine-trouble-code.com/",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9587),
                            ProblemCode = "P18E0",
                            Title = "P18E0 - Reason For P18E0 Code"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9589),
                            Link = "https://www.youtube.com/watch?v=DFp6SjLItH4",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9591),
                            ProblemCode = "P1004",
                            Title = "P1004 - How TO Fix"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9593),
                            Link = "http://p18d0.engine-trouble-code.com/",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9594),
                            ProblemCode = "P18D0",
                            Title = "P18D0 - More Details "
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9596),
                            Link = "https://dot.report/dtc/P18F0",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9597),
                            ProblemCode = "P18F0",
                            Title = "P18F0 - More Details"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9599),
                            Link = "https://www.autocodes.com/b0004_ford.html",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9600),
                            ProblemCode = "C1004",
                            Title = "C1004 - Related to the Driver Knee Bolster Deployment Control"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9602),
                            Link = "https://www.autocodes.com/b0004_ford.html",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9604),
                            ProblemCode = "B0004",
                            Title = "B0004 - Related to the Driver Knee Bolster Deployment Control"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9606),
                            Link = "https://www.autocodes.com/u1004.html",
                            ModifiedDate = new DateTime(2024, 5, 1, 15, 32, 32, 568, DateTimeKind.Local).AddTicks(9607),
                            ProblemCode = "U1004",
                            Title = "U1004 - Intermittent Controller Area Network Bus Performance"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.Fault", b =>
                {
                    b.HasOne("AutoDiag.DataModels.Models.TroubleCode", "TroubleCode")
                        .WithMany()
                        .HasForeignKey("ProblemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoDiag.DataModels.Models.AppUser", "User")
                        .WithMany("Errors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TroubleCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.Reading", b =>
                {
                    b.HasOne("AutoDiag.DataModels.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoDiag.DataModels.Models.AppUser", "User")
                        .WithMany("Readings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.Sensor", b =>
                {
                    b.HasOne("AutoDiag.DataModels.Models.CarSystem", "CarSystem")
                        .WithMany("Sensors")
                        .HasForeignKey("CarSystemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CarSystem");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.TroubleCodeLink", b =>
                {
                    b.HasOne("AutoDiag.DataModels.Models.TroubleCode", "TroubleCode")
                        .WithMany("TroubleCodeLinks")
                        .HasForeignKey("ProblemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TroubleCode");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoDiag.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoDiag.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoDiag.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoDiag.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.AppUser", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.CarSystem", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.Sensor", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("AutoDiag.DataModels.Models.TroubleCode", b =>
                {
                    b.Navigation("TroubleCodeLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
