// <auto-generated />
using System;
using IntelligentDiagnostician.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntelligentDiagnostician.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.CarSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarSystemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CarSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarSystemName = "Engine Performance Sensors",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(662),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(709)
                        },
                        new
                        {
                            Id = 2,
                            CarSystemName = "Environmental Sensors",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(713),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(714)
                        },
                        new
                        {
                            Id = 3,
                            CarSystemName = "Cooling System Sensor ",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(716),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(718)
                        },
                        new
                        {
                            Id = 4,
                            CarSystemName = "Fuel System Sensor",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(720),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 55, DateTimeKind.Local).AddTicks(721)
                        });
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProblemCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProblemCode");

                    b.HasIndex("UserId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("UserId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<float?>("AvgValue")
                        .HasColumnType("real");

                    b.Property<int?>("CarSystemId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("MaxValue")
                        .HasColumnType("real");

                    b.Property<float?>("MinValue")
                        .HasColumnType("real");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CarSystemId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AvgValue = 2.5f,
                            CarSystemId = 3,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4262),
                            MaxValue = 4.5f,
                            MinValue = 0.5f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4304),
                            SensorName = "Engine Coolant Temperature",
                            Unit = "volts"
                        },
                        new
                        {
                            Id = 101,
                            AvgValue = 2.5f,
                            CarSystemId = 4,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4308),
                            MaxValue = 5f,
                            MinValue = 0f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4310),
                            SensorName = "Fuel Level",
                            Unit = "volts"
                        },
                        new
                        {
                            Id = 102,
                            AvgValue = 90.65f,
                            CarSystemId = 2,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4313),
                            MaxValue = 101.3f,
                            MinValue = 80f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4314),
                            SensorName = "Barometric Pressure",
                            Unit = "kPa"
                        },
                        new
                        {
                            Id = 103,
                            AvgValue = 0f,
                            CarSystemId = 2,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4317),
                            MaxValue = 40f,
                            MinValue = -40f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4318),
                            SensorName = "Air in Tank Temperature",
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 104,
                            AvgValue = 4.5f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4321),
                            MaxValue = 5f,
                            MinValue = 4f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4323),
                            SensorName = "MAF (Mass Air Flow)",
                            Unit = "volts"
                        },
                        new
                        {
                            Id = 105,
                            AvgValue = 140f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4327),
                            MaxValue = 250f,
                            MinValue = 30f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4328),
                            SensorName = "Intake Manifold Pressure",
                            Unit = "kPa"
                        },
                        new
                        {
                            Id = 106,
                            AvgValue = 75f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4374),
                            MaxValue = 112f,
                            MinValue = 37f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4375),
                            SensorName = "Engine Power",
                            Unit = "kW"
                        },
                        new
                        {
                            Id = 107,
                            AvgValue = 45f,
                            CarSystemId = 1,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4378),
                            MaxValue = 100f,
                            MinValue = 10f,
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 56, DateTimeKind.Local).AddTicks(4379),
                            SensorName = "Engine Load",
                            Unit = "%"
                        });
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.TroubleCode", b =>
                {
                    b.Property<string>("ProblemCode")
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.HasKey("ProblemCode");

                    b.ToTable("TroubleCodes");

                    b.HasData(
                        new
                        {
                            ProblemCode = "P0079",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(852),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(885),
                            ProblemDescription = "Exhaust Valve Control Circuit Low (Bank 2)",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P2004",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(889),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(891),
                            ProblemDescription = "Problem with the Intake Manifold Runner Control (IMRC) actuator, which controls the airflow into the engine",
                            Severity = 6
                        },
                        new
                        {
                            ProblemCode = "P3000",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(893),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(894),
                            ProblemDescription = "Problem with the battery control system",
                            Severity = 8
                        },
                        new
                        {
                            ProblemCode = "P0078",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(896),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(898),
                            ProblemDescription = "Exhaust Valve Control Circuit (Bank 2)",
                            Severity = 3
                        },
                        new
                        {
                            ProblemCode = "P007E",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(900),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(901),
                            ProblemDescription = "Problem with the Charge Air Cooler Temperature Sensor Circuit",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "P2036",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(904),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(906),
                            ProblemDescription = "Problem with the Exhaust Gas Temperature Sensor Circuit",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P007F",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(908),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(909),
                            ProblemDescription = "Typically related to the fuel temperature sensor",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "P18E0",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(911),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(912),
                            ProblemDescription = "Problem with the Fuel Pressure Sensor Circuit",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "P1004",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(914),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(916),
                            ProblemDescription = "Problem with the Intake Valve Control Solenoid Circuit",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P18D0",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(919),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(920),
                            ProblemDescription = "Problem with the Exhaust Valve Control Solenoid Circuit",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "P18F0",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(922),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(924),
                            ProblemDescription = "Problem with the Turbocharger Boost Control Solenoid Circuit",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "C1004",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(926),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(927),
                            ProblemDescription = "Related to the Driver Knee Bolster Deployment Control",
                            Severity = 5
                        },
                        new
                        {
                            ProblemCode = "B0004",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(929),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(930),
                            ProblemDescription = "Related to the Driver Knee Bolster Deployment Control",
                            Severity = 4
                        },
                        new
                        {
                            ProblemCode = "U1004",
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(932),
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(934),
                            ProblemDescription = "Indicates an intermittent Controller Area Network Bus Transmit Performance",
                            Severity = 8
                        });
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.TroubleCodeLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProblemCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("ProblemCode");

                    b.ToTable("TroubleCodeLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5898),
                            Link = "https://www.obd2pros.com/dtc-codes/p0079/",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5934),
                            ProblemCode = "P0079",
                            Title = "P0079 Code - What Does It Mean?"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5938),
                            Link = "https://www.engine-codes.com/p0079.html",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5939),
                            ProblemCode = "P0079",
                            Title = "P0079 Code - Meaning, Causes, & Symptoms"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5941),
                            Link = "https://cartreatments.com/p2004-code-imrc-issue-symptoms-causes-and-fixes/",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5943),
                            ProblemCode = "P2004",
                            Title = "P2004 Code - IMRC Issue"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5945),
                            Link = "https://www.rxmechanic.com/p3000-error-code/",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5946),
                            ProblemCode = "P3000",
                            Title = "P3000 Error Code - What Does It Mean?"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5948),
                            Link = "https://www.troublecodes.net/pcodes/p3000/",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5949),
                            ProblemCode = "P3000",
                            Title = "P3000 - Manufacturer Controlled DTC Bank 1"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5953),
                            Link = "https://www.troublecodes.net/pcodes/p0078/",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5955),
                            ProblemCode = "P0078",
                            Title = "P0078 - Exhaust Valve Control Circuit"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5957),
                            Link = "https://www.obd-codes.com/p007e",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5958),
                            ProblemCode = "P007E",
                            Title = "P007E - Charge Air Cooler Temp. Sensor Circuit"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5960),
                            Link = "https://www.obd-codes.com/p2036",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5961),
                            ProblemCode = "P2036",
                            Title = "P2036 - Exhaust Gas Temp. Sensor Circuit"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5963),
                            Link = "https://partsavatar.ca/p007f-obd-ii-trouble-code-charge-air-cooler-temperature-sensor-bank-1-bank-2-correlation-solution",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5965),
                            ProblemCode = "P007F",
                            Title = "P007F - Charge Air Cooler Temp. Sensor Correlation"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5968),
                            Link = "http://p18e0.engine-trouble-code.com/",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5969),
                            ProblemCode = "P18E0",
                            Title = "P18E0 - Reason For P18E0 Code"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5971),
                            Link = "https://www.youtube.com/watch?v=DFp6SjLItH4",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5972),
                            ProblemCode = "P1004",
                            Title = "P1004 - How TO Fix"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5974),
                            Link = "http://p18d0.engine-trouble-code.com/",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5976),
                            ProblemCode = "P18D0",
                            Title = "P18D0 - More Details "
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5978),
                            Link = "https://dot.report/dtc/P18F0",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5979),
                            ProblemCode = "P18F0",
                            Title = "P18F0 - More Details"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5981),
                            Link = "https://www.autocodes.com/b0004_ford.html",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5982),
                            ProblemCode = "C1004",
                            Title = "C1004 - Related to the Driver Knee Bolster Deployment Control"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5985),
                            Link = "https://www.autocodes.com/b0004_ford.html",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(5986),
                            ProblemCode = "B0004",
                            Title = "B0004 - Related to the Driver Knee Bolster Deployment Control"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(6032),
                            Link = "https://www.autocodes.com/u1004.html",
                            ModifiedDate = new DateTime(2024, 4, 30, 16, 52, 0, 57, DateTimeKind.Local).AddTicks(6034),
                            ProblemCode = "U1004",
                            Title = "U1004 - Intermittent Controller Area Network Bus Performance"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.Error", b =>
                {
                    b.HasOne("IntelligentDiagnostician.DataModels.Models.TroubleCode", "TroubleCode")
                        .WithMany()
                        .HasForeignKey("ProblemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelligentDiagnostician.DataModels.Models.AppUser", "User")
                        .WithMany("Errors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TroubleCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.Reading", b =>
                {
                    b.HasOne("IntelligentDiagnostician.DataModels.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelligentDiagnostician.DataModels.Models.AppUser", "User")
                        .WithMany("Readings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.Sensor", b =>
                {
                    b.HasOne("IntelligentDiagnostician.DataModels.Models.CarSystem", "CarSystem")
                        .WithMany("Sensors")
                        .HasForeignKey("CarSystemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CarSystem");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.TroubleCodeLink", b =>
                {
                    b.HasOne("IntelligentDiagnostician.DataModels.Models.TroubleCode", "TroubleCode")
                        .WithMany("TroubleCodeLinks")
                        .HasForeignKey("ProblemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TroubleCode");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IntelligentDiagnostician.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IntelligentDiagnostician.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelligentDiagnostician.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IntelligentDiagnostician.DataModels.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.AppUser", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.CarSystem", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.Sensor", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("IntelligentDiagnostician.DataModels.Models.TroubleCode", b =>
                {
                    b.Navigation("TroubleCodeLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
